// app/layout.tsx
import "./globals.css";
import { Bebas_Neue, Poppins, Outfit } from "next/font/google";

// Bebas Neue (for Headlines)
const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
  display: "swap",
});

// Poppins (for body text / secondary font)
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

// Outfit (for buttons / alternative text)
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit",
  display: "swap",
});

export const metadata = {
  title: "Osman's Portfolio",
  description: "Generated by create next app and modified by Osman",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bebas.variable} ${poppins.variable} ${outfit.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
